sudo: false
language: python

python:
  - 3.6

cache:
  directories:
    - Qt

addons:
  apt:
    packages:
      - tree
      - virtualenv
  artifacts: true
  paths:
    - dist/*

before_install:
  - tree -L 4
  - if [ ! -e Qt/5.9.1 ] ; then
        rm -rf Qt ;
        wget -nv http://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run ;
        chmod +x ./qt-opensource-linux-x64-5.9.1.run ;
        ./qt-opensource-linux-x64-5.9.1.run --platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
    fi
  - wget -nv https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
  - mv squashfs-root linuxdeployqt

script:
  - python venv.py
  - venv/bin/python setup.py bdist_wheel
  - tree -L 4
