sudo: false
language: python

python:
  - 3.6
  - 3.5

cache:
  directories:
    - deployed_qt

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - tree
      - python-virtualenv
      - python3.6

  artifacts:
    s3_region: $ARTIFACTS_REGION
    paths:
      - $(ls $TRAVIS_BUILD_DIR/dist/*.whl | tr "\n" ":")

env:
  matrix:
    - PYQT5_VERSION=5.9
    - PYQT5_VERSION=5.8.1
    - PYQT5_VERSION=5.7.1

before_install:
  - tree -L 4
  - virtualenv -p python3.6 venv
  - venv/bin/python -m pip install ./pyqt5toolsbuild
  - venv/bin/python -c 'import sys; print(sys.version); print(sys.executable)'
  - venv/bin/python -m pip freeze
  - wget -nv https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
  - mv squashfs-root linuxdeployqt
  - venv/bin/before_install

script:
  - git fetch --unshallow
  - venv/bin/buildlinux
  - virtualenv -p python target_venv
  - target_venv/bin/python -m pip install requests==2.13.0
  - target_venv/bin/python -m pip install vcversioner==2.16.0.0
  - target_venv/bin/python -m pip install wheel==0.30.0a0
  - target_venv/bin/python -c 'import sys; print(sys.version); print(sys.executable)'
  - target_venv/bin/python -m pip freeze
  - target_venv/bin/python setup.py bdist_wheel

before_cache:
  - tree -L 4
