sudo: true
language: python

python:
  - 3.6
  - 3.5

cache:
  directories:
    - deployed_qt

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - tree
      - python-virtualenv
      - python3.6
      - libmysqlclient-dev

  artifacts:
    s3_region: $ARTIFACTS_REGION
    paths:
      - $(ls $TRAVIS_BUILD_DIR/dist/*.whl | tr "\n" ":")

env:
  matrix:
    - PYQT5_VERSION=5.9
    - PYQT5_VERSION=5.8.1
#    - PYQT5_VERSION=5.7.1

before_install:
  - tree -L 4
  - virtualenv -p python3.6 venv
  - venv/bin/python -m pip install ./pyqt5toolsbuild
  - venv/bin/python -c 'import sys; print(sys.version); print(sys.executable)'
  - venv/bin/python -m pip freeze
  - sudo add-apt-repository --yes $(venv/bin/beineri ppa --version $(venv/bin/version qt --version $PYQT5_VERSION))
  - sudo apt-get update -qq
  - sudo apt-get install -y qt$(venv/bin/version exact --remove-dots --levels 2 --version $(venv/bin/version qt --version $PYQT5_VERSION))-meta-full
  - wget -nv https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
  - mv squashfs-root linuxdeployqt
  - mkdir LD_LIBRARY_PATH
  - ln -s /lib/x86_64-linux-gnu/libssl.so.1.0.0 LD_LIBRARY_PATH/libssl.so.10
  - ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 LD_LIBRARY_PATH/libcrypto.so.10
#  libbluetooth.so.3
  - if [ -z "$LD_LIBRARY_PATH" ]; then
      export LD_LIBRARY_PATH=$PWD/LD_LIBRARY_PATH;
    else
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/LD_LIBRARY_PATH;
    fi
  - echo LD_LIBRARY_PATH    $LD_LIBRARY_PATH
  - ldconfig -p
  - venv/bin/before_install

script:
  - git fetch --unshallow
  - venv/bin/buildlinux --venv-bin target_venv/bin
  - virtualenv -p python target_venv
  - target_venv/bin/python -m pip install requests==2.13.0
  - target_venv/bin/python -m pip install vcversioner==2.16.0.0
  - target_venv/bin/python -m pip install wheel==0.30.0a0
  - target_venv/bin/python -c 'import sys; print(sys.version); print(sys.executable)'
  - target_venv/bin/python -m pip freeze
  - target_venv/bin/python setup.py bdist_wheel

before_cache:
  - tree -L 4
