image: Visual Studio 2015

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\run_with_env.cmd"

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-Variable -Name ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - ps: Get-Variable -Name ENABLE_RDP
  - echo ENABLE_RDP %ENABLE_RDP%
  - "c:\\python36\\python venv.py"
  # Build the compiled extension
  - "venv\\Scripts\\python setup.py build_wheel"

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-Variable -Name ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
